### ISSUE TITLE
Support for Firefox

### ISSUE THREAD

**Issue by thamognya** [DannyCol/Colab-Themes#1]
I really like this extension when using chromium, but once I switched from chromium to firefox-based alternatives (like firefox, librewolf, gnu icecat and etc.) I was not able to use this extension on google colab. I was wondering if a port for firefox would be made.

**Comment by DannyCol** [comment]
Hello. I'm glad you like this extension! I completely understand the switch to Firefox. Many people are switching due to the manifest-v2 support that allows extensions to have control over networking requests, which allows extensions to block requests that are for ads. This kind of control over network requests is no longer possible in manifest-v3, but it is not the only difference between manifest-v2 and manifest-v3. The API differs in many ways between the two versions, and it would require a lot of work for me to change I am doing in manifest-v3 and do the same in manifest-v2. Mozilla has said it expects Firefox to have manifest-v3 support (but still support manifest-v2, unlike Chrome)  ["by the end of 2022"](https://blog.mozilla.org/addons/2022/05/18/manifest-v3-in-firefox-recap-next-steps/), which is not that far away. So, rather than learn a new API, I have chosen to wait until Mozilla updates Firefox.
