### ISSUE TITLE
Github-Dark-Theme

### ISSUE THREAD

**Issue by PRigas96** [DannyCol/Colab-Themes#2]
Hey, I'm really enjoying this project and was just wandering if by any chance you could add github-dark-theme?

**Comment by DannyCol** [comment]
Hello. I'm glad you enjoy it! Sorry I took so long to respond; I have been very busy lately. I am not going to add a new theme to the extension since it already has 56, but in a future update, I am going to replace the current instructions on importing a theme with instructions contained in [this colab notebook](https://colab.research.google.com/drive/1Y3Ep4lwPUb0YIR1ac-kdRTX-qLHhIEtn?usp=sharing) I made. This notebook contains the specific theme you want to use, so you should be able to run all the cells as they are and then follow the few manual instructions at the end, but if you need any help, feel free to reach out again.

**Comment by PRigas96** [comment]
Hey thanks for answering.I just tried ur notebook. I wanna say its really nice written! A few notes:
when using bash convert some errors pop up but they are irrelevant to the process.

The thing is after doing the process the generated files are usually to big for the app. You have limit the size to 21 KB in popup:

`    if (theme_json.length > 21000) {
      errorMsg.innerHTML = 'The file is too large.<br/>';
      return;
`
is it possible to make it larget ? I have made files with up to 50 KB. If there is a reason for this limit, are there some general guidlines for what to delete ? (I have tried to compress it by deleting spaces etc)

When deleting random lines myself, i have managed to create themes that work and some who doesnt.

**Comment by DannyCol** [comment]
The reason the limit exists is because the `theme_json` file is not stored as a file, but as text, split up into (right now, up to 3) variables, which have [limitations](https://developer.chrome.com/docs/extensions/reference/storage/#property-sync) like the maximum size of each variable, 8K, and the maximum variable reads per minute. The main benefit of doing it this way is that your theme custom theme choice is synced across any chrome browser you log into with your chrome account. I'll increase the max size it can be through either increasing the number of variables or some more efficient way. I'll try to do this over the weekend.

In the meantime, I can suggest you try deleting non-Python language specific parts of the `theme_json` file, if the theme has that. If it does have what I am talking about, it would probably have comments around each of the language-specific parts, so you could find the parts to delete by deleting those areas. Also, you don't need to compress it by deleting spaces, the app does that itself in the `let theme_json = JSON.stringify(JSON.parse(event.target.result))` line. I would suggest just waiting until I increase the limit on this though.
